#!/usr/bin/env bash

set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
wallpaper_source="$script_dir/wallpaper.png"

if [[ ! -r /etc/os-release ]]; then
  printf 'Error: cannot identify this Linux distribution.\n' >&2
  exit 1
fi

# shellcheck disable=SC1091
source /etc/os-release
if [[ ${ID:-} != arch && " ${ID_LIKE:-} " != *" arch "* ]]; then
  printf 'Error: this installer supports Arch-based Linux only (detected: %s).\n' "${ID:-unknown}" >&2
  exit 1
fi

if ! command -v pacman >/dev/null 2>&1; then
  printf 'Error: pacman is not available.\n' >&2
  exit 1
fi

if [[ ! -r $wallpaper_source ]]; then
  printf 'Error: wallpaper not found: %s\n' "$wallpaper_source" >&2
  exit 1
fi

packages_file="$script_dir/packages.conf"
if [[ ! -r $packages_file ]]; then
  printf 'Error: package list not found: %s\n' "$packages_file" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$packages_file"

missing_packages=()
for package in "${packages[@]}"; do
  if pacman -Qq "$package" >/dev/null 2>&1; then
    printf 'Skipping %s: already installed.\n' "$package"
  else
    missing_packages+=("$package")
  fi
done

if ((${#missing_packages[@]} == 0)); then
  printf 'Everything is already installed.\n'
else
  printf 'Updating package databases and installing: %s\n' "${missing_packages[*]}"
  sudo pacman -Syu --needed "${missing_packages[@]}"
fi

install_user=${SUDO_USER:-${USER:-$(id -un)}}
if pacman -Qq docker >/dev/null 2>&1; then
  printf 'Enabling and starting Docker.\n'
  sudo systemctl enable --now docker.service

  user_groups=" $(id -nG "$install_user") "
  if [[ $user_groups == *" docker "* ]]; then
    printf 'Skipping Docker group setup: %s is already a member.\n' "$install_user"
  else
    printf 'Adding %s to the Docker group.\n' "$install_user"
    sudo usermod -aG docker "$install_user"
    printf 'Log out and back in before running Docker without sudo.\n'
  fi
fi

if ! command -v yay >/dev/null 2>&1; then
  printf 'Error: yay is not available after package installation.\n' >&2
  exit 1
fi

missing_yay_packages=()
for package in "${yay_packages[@]}"; do
  if pacman -Qq "$package" >/dev/null 2>&1; then
    printf 'Skipping %s: already installed.\n' "$package"
  else
    missing_yay_packages+=("$package")
  fi
done

if ((${#missing_yay_packages[@]} == 0)); then
  printf 'All yay packages are already installed.\n'
else
  printf 'Installing with yay: %s\n' "${missing_yay_packages[*]}"
  yay -S --needed --noconfirm "${missing_yay_packages[@]}"
fi

sddm_theme_dir="/usr/share/sddm/themes/sddm-astronaut-theme"
sddm_theme_repo="https://github.com/Keyitdev/sddm-astronaut-theme.git"

printf 'Installing the SDDM astronaut theme.\n'
if [[ -d $sddm_theme_dir/.git ]]; then
  sudo git -C "$sddm_theme_dir" pull --ff-only
else
  sudo git clone --depth 1 "$sddm_theme_repo" "$sddm_theme_dir"
fi

sudo cp -r "$sddm_theme_dir/Fonts/." /usr/share/fonts/
sudo sed -i \
  's|^ConfigFile=.*|ConfigFile=Themes/japanese_aesthetic.conf|' \
  "$sddm_theme_dir/metadata.desktop"

sudo install -d -m 0755 /etc/sddm.conf.d
printf '[Theme]\nCurrent=sddm-astronaut-theme\n' |
  sudo tee /etc/sddm.conf.d/10-sddm-theme.conf >/dev/null
printf '[General]\nInputMethod=qtvirtualkeyboard\n' |
  sudo tee /etc/sddm.conf.d/20-sddm-virtual-keyboard.conf >/dev/null
sudo systemctl enable sddm.service

hypr_config="$HOME/.config/hypr/hyprland.lua"
fish_config="$HOME/.config/fish/config.fish"

if [[ -f $hypr_config ]]; then
  sed -i \
    -e '/hl\.config({ autogenerated = true })/d' \
    -e 's/local terminal    = "kitty"/local terminal    = "alacritty"/' \
    -e 's/local fileManager = "dolphin"/local fileManager = "nemo"/' \
    -e 's/local menu        = "hyprlauncher"/local menu        = "wofi --show drun"/' \
    -e 's/kb_layout  = "us"/kb_layout  = "de"/' \
    -e 's/local mainMod = "ALT".*/local mainMod = "SUPER"/' \
    -e 's/hl.bind(mainMod \.\. " + Q", hl.dsp.exec_cmd(terminal))/hl.bind(mainMod .. " + Q", hl.dsp.window.close())/' \
    -e 's/hl.bind(mainMod \.\. " + S",.*hl.dsp.workspace.toggle_special("magic"))/hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("hypr-shortcuts"))/' \
    "$hypr_config"

  if ! grep -Fq 'mainMod .. " + Return"' "$hypr_config"; then
    sed -i '/mainMod \.\. " + Q"/a hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))' "$hypr_config"
  fi

  if ! grep -Fq 'mainMod .. " + Space"' "$hypr_config"; then
    sed -i '/mainMod \.\. " + Return"/a hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(menu))' "$hypr_config"
  fi

  if ! grep -Fq 'mainMod .. " + S", hl.dsp.exec_cmd("hypr-shortcuts")' "$hypr_config"; then
    sed -i '/mainMod \.\. " + Space"/a hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("hypr-shortcuts"))' "$hypr_config"
  fi

  if ! grep -Fq 'hl.exec_cmd("waybar")' "$hypr_config"; then
    sed -i '/Configuring\/Basics\/Autostart/a\
\
hl.on("hyprland.start", function()\
    hl.exec_cmd("waybar")\
end)' "$hypr_config"
  fi

  if ! grep -Fq 'hl.exec_cmd("hyprpaper")' "$hypr_config"; then
    sed -i '/Configuring\/Basics\/Autostart/a\
\
hl.on("hyprland.start", function()\
    hl.exec_cmd("hyprpaper")\
end)' "$hypr_config"
  fi

  if ! grep -Fq 'name = "shortcut-viewer"' "$hypr_config"; then
    sed -i '/-- Layer rules also return a handle\./i\
hl.window_rule({\
    name = "shortcut-viewer",\
    match = { class = "wofi" },\
    float = true,\
    size = "70% 75%",\
    center = true,\
})\
' "$hypr_config"
  fi

  if ! grep -Fq 'require("installer-shortcuts")' "$hypr_config"; then
    printf '\nrequire("installer-shortcuts")\n' >>"$hypr_config"
  fi
else
  printf 'Warning: %s does not exist; start Hyprland once to generate it.\n' "$hypr_config" >&2
fi

mkdir -p "$HOME/.config/hypr"
wallpaper_file="$HOME/.config/hypr/wallpaper.png"
install -m 0644 "$wallpaper_source" "$wallpaper_file"
cat >"$HOME/.config/hypr/hyprpaper.conf" <<EOF
preload = $wallpaper_file
wallpaper = ,$wallpaper_file
EOF

hyprland_file="$script_dir/hyprland/installer-shortcuts.lua"
if [[ ! -r $hyprland_file ]]; then
  printf 'Error: Hyprland configuration not found: %s\n' "$hyprland_file" >&2
  exit 1
fi
install -m 0644 "$hyprland_file" "$HOME/.config/hypr/installer-shortcuts.lua"

if ! grep -Fq '# Start Hyprland after a local login on the first virtual terminal.' "$fish_config"; then
  printf '\n%s\n%s\n%s\n%s\n' \
    '# Start Hyprland after a local login on the first virtual terminal.' \
    'if status is-login; and test -z "$WAYLAND_DISPLAY"; and test "$XDG_VTNR" = 1' \
    '    exec start-hyprland' \
    'end' >>"$fish_config"
fi

sed -i 's/^[[:space:]]*exec Hyprland$/    exec start-hyprland/' "$fish_config"

mkdir -p "$HOME/.local/bin"
cat >"$HOME/.local/bin/hypr-shortcuts" <<'EOF'
#!/usr/bin/env bash

set -euo pipefail

hyprctl binds -j | jq -r -f "$HOME/.config/wofi/shortcuts.jq" |
  wofi --dmenu --normal-window --insensitive --no-custom-entry \
    --prompt 'Search shortcuts' \
    --style "$HOME/.config/wofi/shortcuts.css" \
    --width 70% --height 75% >/dev/null
EOF
chmod +x "$HOME/.local/bin/hypr-shortcuts"

mkdir -p "$HOME/.config/wofi"
cat >"$HOME/.config/wofi/shortcuts.jq" <<'EOF'
def modifier_names:
  [
    if (((.modmask / 64) | floor) % 2) == 1 then "Super" else empty end,
    if (((.modmask / 8) | floor) % 2) == 1 then "Alt" else empty end,
    if (((.modmask / 4) | floor) % 2) == 1 then "Ctrl" else empty end,
    if (.modmask % 2) == 1 then "Shift" else empty end
  ] | join(" + ");

def pretty_key:
  .key |
  if . == "Return" then "Enter"
  elif . == "left" then "Left Arrow"
  elif . == "right" then "Right Arrow"
  elif . == "up" then "Up Arrow"
  elif . == "down" then "Down Arrow"
  elif . == "mouse_down" then "Scroll Down"
  elif . == "mouse_up" then "Scroll Up"
  elif . == "mouse:272" then "Left Drag"
  elif . == "mouse:273" then "Right Drag"
  elif . == "XF86AudioRaiseVolume" then "Volume Up"
  elif . == "XF86AudioLowerVolume" then "Volume Down"
  elif . == "XF86AudioMute" then "Volume Mute"
  elif . == "XF86AudioMicMute" then "Microphone Mute"
  elif . == "XF86MonBrightnessUp" then "Brightness Up"
  elif . == "XF86MonBrightnessDown" then "Brightness Down"
  elif . == "XF86AudioNext" then "Media Next"
  elif . == "XF86AudioPause" then "Media Pause"
  elif . == "XF86AudioPlay" then "Media Play"
  elif . == "XF86AudioPrev" then "Media Previous"
  else . end;

.[] |
(modifier_names) as $mods |
(pretty_key) as $key |
(if $mods == "" then $key else "\($mods) + \($key)" end) as $combo |
(
  if .description != "" then .description
  elif .modmask == 64 and .key == "Q" then "Close focused window"
  elif .modmask == 64 and .key == "Return" then "Open Alacritty"
  elif .modmask == 64 and (.key == "Space" or .key == "R") then "Open Wofi"
  elif .modmask == 64 and .key == "C" then "Close focused window"
  elif .modmask == 64 and .key == "S" then "Show shortcut viewer"
  elif .modmask == 64 and .key == "M" then "Open shutdown menu"
  elif .modmask == 64 and .key == "E" then "Open Nemo"
  elif .modmask == 64 and .key == "V" then "Toggle floating window"
  elif .modmask == 64 and .key == "P" then "Toggle pseudo tiling"
  elif .modmask == 64 and .key == "J" then "Toggle split direction"
  elif .modmask == 64 and (.key == "left" or .key == "right" or .key == "up" or .key == "down") then "Move focus"
  elif .modmask == 64 and (.key | test("^[0-9]$")) then "Switch workspace"
  elif .modmask == 65 and (.key | test("^[0-9]$")) then "Move window to workspace"
  elif .modmask == 65 and .key == "S" then "Move window to special workspace"
  elif .key == "mouse_down" or .key == "mouse_up" then "Cycle workspaces"
  elif .key == "mouse:272" then "Move window"
  elif .key == "mouse:273" then "Resize window"
  elif .key == "XF86AudioRaiseVolume" or .key == "XF86AudioLowerVolume" then "Adjust volume"
  elif .key == "XF86AudioMute" then "Toggle audio mute"
  elif .key == "XF86AudioMicMute" then "Toggle microphone mute"
  elif .key == "XF86MonBrightnessUp" or .key == "XF86MonBrightnessDown" then "Adjust brightness"
  elif (.key | startswith("XF86Audio")) then "Control media playback"
  elif .dispatcher != "__lua" then "\(.dispatcher) \(.arg)"
  else "Configured Hyprland shortcut"
  end
) as $action |
"\($combo)    \($action)"
EOF

cat >"$HOME/.config/wofi/shortcuts.css" <<'EOF'
window {
  margin: 0;
  border: 2px solid #89b4fa;
  border-radius: 16px;
  color: #cdd6f4;
  background-color: #11111b;
  font-family: sans-serif;
  font-size: 15px;
}

#outer-box {
  padding: 18px;
}

#input {
  margin-bottom: 14px;
  padding: 12px 16px;
  border: 1px solid #313244;
  border-radius: 10px;
  color: #ffffff;
  background-color: #1e1e2e;
}

#entry {
  margin: 3px 0;
  padding: 11px 14px;
  border-radius: 9px;
}

#entry:selected {
  color: #11111b;
  background-color: #89b4fa;
}

#text {
  padding-left: 4px;
}

#text:selected {
  color: #11111b;
}
EOF

waybar_dir="$HOME/.config/waybar"
mkdir -p "$waybar_dir"

if [[ ! -e $waybar_dir/config.jsonc ]]; then
  cat >"$waybar_dir/config.jsonc" <<'EOF'
{
  "layer": "top",
  "position": "top",
  "height": 34,
  "modules-left": [],
  "modules-center": ["hyprland/workspaces"],
  "modules-right": [],
  "hyprland/workspaces": {
    "format": "{id}",
    "persistent-workspaces": {
      "*": [1, 2, 3, 4, 5, 6, 7, 8, 9]
    }
  }
}
EOF
fi

if [[ ! -e $waybar_dir/style.css ]]; then
  cat >"$waybar_dir/style.css" <<'EOF'
* {
  border: none;
  border-radius: 0;
  font-family: sans-serif;
  font-size: 14px;
  min-height: 0;
}

window#waybar {
  background: rgba(20, 20, 20, 0.92);
}

#workspaces button {
  padding: 0 12px;
  color: #888888;
  background: transparent;
}

#workspaces button.active {
  color: #ffffff;
  background: #3b82f6;
}

#workspaces button:hover {
  color: #ffffff;
  background: #333333;
}
EOF
fi

printf 'Installation and configuration complete.\n'
