# Packages installed from the Arch repositories.
packages=(
  hyprland
  hyprpaper
  waybar
  wofi
  hyprshot
  jq
  yay
  alacritty
  firefox
  nemo
  vlc
  krita
  blender
  meld
  pavucontrol
  btop
  shelly
  brightnessctl
  playerctl
  hyprshutdown
  libreoffice-fresh
  docker
  docker-compose
  sddm
  qt6-svg
  qt6-virtualkeyboard
  qt6-multimedia-ffmpeg
  git
)

# Packages installed from the AUR with yay.
yay_packages=(
  helium-browser-bin
  visual-studio-code-bin
  cherry-studio-bin
)
